- name: Update hostname
  hostname: name="{{hostname_hostname}}"

- name: Update /etc/hostname
  template: src=hostname.j2 dest=/etc/hostname owner=root group=root mode=0644

- name: Update /etc/hosts pt. 1 
  lineinfile:
    dest: /etc/hosts
    regexp: "^127.0.0.1"
    line: "127.0.0.1 {{hostname_hostname}}{% if hostname_hostname != hostname_hostname_short %} {{hostname_hostname_short}}{% endif %} localhost"

- name: Update /etc/hosts pt. 2
  lineinfile: line="{{item.value}} {{item.key}}" dest=/etc/hosts
  with_dict: hostname_hosts
